// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmWEbybKBt3sOh9p9yVCJD62O5kEdhRwY',
    appId: '1:626389782090:web:a4a9e201c363751c8ba0b3',
    messagingSenderId: '626389782090',
    projectId: 'fir-operation-6fa10',
    authDomain: 'fir-operation-6fa10.firebaseapp.com',
    storageBucket: 'fir-operation-6fa10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2iwj9aK-aLrW_bQ8ya99fBB0G1Jcx5aY',
    appId: '1:626389782090:android:649d7e5fb803b5848ba0b3',
    messagingSenderId: '626389782090',
    projectId: 'fir-operation-6fa10',
    storageBucket: 'fir-operation-6fa10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ6n2Ex18RPtT1QYY00RpU9Ios9iktG1c',
    appId: '1:626389782090:ios:04604c9e75a434b48ba0b3',
    messagingSenderId: '626389782090',
    projectId: 'fir-operation-6fa10',
    storageBucket: 'fir-operation-6fa10.appspot.com',
    iosClientId: '626389782090-i9vcn3pslgl1krimmb02vm1ppo5856kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreOperation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ6n2Ex18RPtT1QYY00RpU9Ios9iktG1c',
    appId: '1:626389782090:ios:04604c9e75a434b48ba0b3',
    messagingSenderId: '626389782090',
    projectId: 'fir-operation-6fa10',
    storageBucket: 'fir-operation-6fa10.appspot.com',
    iosClientId: '626389782090-i9vcn3pslgl1krimmb02vm1ppo5856kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreOperation',
  );
}
